---
charts:
  charts.longhorn.io:
    - longhorn
  kubernetes-sigs.github.io/nfs-subdir-external-provisioner:
    - nfs-subdir-external-provisioner
  wutong-paas.github.io/helm-charts:
  kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner:
