name: sync

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-chart:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
        cache: 'pip' # caching pip dependencies
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: generate_sync_yaml
      timeout-minutes: 30
      env:
        CHART_REPO: ${{ secrets.CHART_REPO }}
        USER: ${{ secrets.CHART_USERNAME }}
        PASS: ${{ secrets.CHART_PASSWORD }}
      run: |
        python generate_sync_yaml.py
        ls -al

    - name: build image
      uses: docker/build-push-action@v2
      with:
        tags: chart-sync:latest
        build-args: |
          CHART_REPO=${{ secrets.CHART_REPO }}
          USER=${{ secrets.CHART_USERNAME }}
          PASS=${{ secrets.CHART_PASSWORD }}
        push: false
        
    - name: chart sync
      uses: addnab/docker-run-action@v3
      with:
        image: chart-sync:latest
        run: |
          sh -x /entrypoint.sh
