name: sync

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync-chart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build image
      uses: docker/build-push-action@v4
      with:
        tags: chart-sync:latest
        build-args: |
          CHART_REPO=${{ secrets.CHART_REPO }}
          CHART_USERNAME=${{ secrets.CHART_USERNAME }}
          CHART_PASSWORD=${{ secrets.CHART_PASSWORD }}
          CONTAINER_REGISTRY=${{ secrets.CONTAINER_REGISTRY }}
          CONTAINER_REPO=${{ secrets.CONTAINER_REPO }}
        push: false
        
    - name: chart sync
      uses: addnab/docker-run-action@v3
      with:
        image: chart-sync:latest
        run: |
          sh /entrypoint.sh
